# Generated by Django 4.2.10 on 2024-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
