# Generated by Django 4.2.10 on 2024-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_wallet_id_alter_wallet_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.CharField(max_length=255),
        ),
    ]
