# Generated by Django 4.2.10 on 2024-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wallet_id_alter_wallet_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
