# Generated by Django 4.2.10 on 2024-02-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wallet_disabled_at_alter_wallet_enabled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
