# Generated by Django 4.2.10 on 2024-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_wallet_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='reference_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
