# Generated by Django 4.2.10 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ledger_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
